favicon: /assets/img/identity/favicon.svg
primaryLogo: /assets/img/identity/primary-logo-light.svg

main_menu_settings:
  menu_items:
    - title: About
      icon: info
      submenu_items:
        - title: The Count
          url: /about
          icon: person
        - title: Krigsvold, Borbolla, and Matikonis
          url: /krigsvold-matikonis
          icon: landscape
        - title: Mission and Method
          url: /mission-and-method
          icon: explore
        - title: Heraldry
          url: /heraldry
          icon: shield
        - title: Frequently Asked Questions
          url: /faq
          icon: quiz
    - title: Climate Impacts
      icon: layers
      submenu_items:
        - title: Rapid Ice Melt
          url: /rapid-ice-melt
          icon: ac_unit
        - title: Warming Continents
          url: /warming-continents
          icon: thermostat
        - title: Endangered Ecosystems
          url: /endangered-ecosystems
          icon: pets
        - title: Carbon Sequestration
          url: /carbon-sequestration
          icon: co2
        - title: Research and Response
          url: /research-response
          icon: science
    - title: Support and Participation
      icon: handshake
      submenu_items:
        - title: The Fellowship
          url: /fellowship
          icon: school
        - title: Research Support
          url: /research-support
          icon: analytics
        - title: Get Involved
          url: /get-involved
          icon: groups
    - title: News
      url: /news
      icon: newspaper


footer_menu_settings:
  menu_items:
    - title: The House
      submenu_items:
      - title: House of Basu-Howard
        url: https://basuhoward.org
        target: _blank
      - title: Manor of Dungeon in Kent
        url: https://dungeonmanor.uk
        target: _blank
      - title: Dr James P. Howard, II
        url: https://jameshoward.us
        target: _blank
    - title: Westarctica
      submenu_items:
      - title: Grand Duchy of Westarctica
        url: https://www.westarctica.info
        target: _blank
      - title: Encyclopedia Westarctica
        url: https://www.westarctica.wiki
        target: _blank
      - title: Westarctica, Inc.
        url: https://www.westarctica.org
        target: _blank
    - title: Social Media
      submenu_items:
      - title: Facebook
        url: https://www.facebook.com/CountKrigsvoldWestarctica
        target: _blank
        relationship: me
      - title: Bluesky
        url: https://bsky.app/profile/krigsvold.org
        target: _blank
        relationship: me
      - title: Mastodon
        url: https://mastodon.social/@krigsvold
        target: _blank
        relationship: me
      - title: Pinterest
        url: https://pinterest.com/countofkrigsvold
        target: _blank
        relationship: me
    - title: Legal
      submenu_items:
      - title: Privacy
        url: /privacy-policy
        relationship: privacy-policy
      - title: Terms of Use
        url: /terms-of-use
      - title: Copyright
        url: /copyright

social_media:
  - name: Twitter
    icon: twitter
    url: https://twitter.com/countkrigsvold
  - name: Facebook
    icon: facebook
    url: https://www.facebook.com/CountKrigsvoldWestarctica

footer_settings:
  footer_tagline: A website of the House of Basu-Howard
